export const COUPON_CODES = {
  BFRIDAY25 : 'BFRIDAY25',
  WEEKEND25: 'WEEKEND25',
  SUMMER50: 'SUMMER50',
  FALL25: 'FALL25',
  CHRISTMAS25: 'CHRISTMAS25',
  NEWYEAR25: 'NEWYEAR25',
  HALLOWEEN25: 'HALLOWEEN25',
} as const

export type CouponCode = (typeof COUPON_CODES)[keyof typeof COUPON_CODES]
